# Generated by Django 3.0.6 on 2020-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_auto_20200612_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=30, verbose_name='The Name'),
        ),
    ]
